urls = {
'https://pensionsmyndigheten.se': 'Pensionsmyndigheten',
"https://skatteverket.se": "Skatteverket",
"https://arbetsformedlingen.se": "Arbetsförmedlingen",
"https://forsakringskassan.se": "Försäkringskassan",
"https://polisen.se": "Polisen",
"https://onep.se": "Överklagandenämnden för etikprövning",
"https://www.mtfa.se": "Myndigheten för totalförsvarsanalys",
"https://www.migrationsverket.se": "Migrationsverket",
"https://www.riksdagen.se": "Riksdagen",
"https://www.riksbank.se": "Sveriges Riksbank",
"https://www.riksrevisionen.se": "Riksrevisionen",
"https://www.arbetsgivarverket.se": "Arbetsgivarverket",
"https://av.se": "Arbetsmiljöverket",
'https://www.arn.se': 'Allmänna Reklamationsnämnden',
'https://www.vetansvar.se':	'Ansvarsnämnden För Djurens Hälso- Och Sjukvård',
'https://www.arbetsformedlingen.se':'Arbetsförmedlingen',
'https://www.av.se':'Arbetsmiljöverket',
'https://www.arvsfonden.se':'Arvfondsdelegationen',
'https://www.barnombudsmannen.se':'Barnombudsmannen',
'https://www.bth.se':	'Blekinge Tekniska Högskola',
'https://www.bfn.se':	'Bokföringsnämnden',
'https://www.bolagsverket.se':	'Bolagsverket',
'https://www.boverket.se':	'Boverket',
'https://www.bra.se':	'Brottsförebyggande Rådet',
'https://www.brottsoffermyndigheten.se':	'Brottsoffermyndigheten',
'https://www.cdfn.se':	'Centrala Djurförsöksetiska Nämnden',
'https://www.csn.se':	'Centrala Studiestödsnämnden',
'https://www.do.se':	'Diskrimineringsombudsmannen',
'https://www.domstol.se':	'Sveriges Domstolar',
'https://www.ehalsomyndigheten.se':	'E-Hälsomyndigheten',
'https://www.ekobrottsmyndigheten.se':	'Ekobrottsmyndigheten',
'https://www.esv.se':	'Ekonomistyrningsverket',
'https://www.elsakerhetsverket.se':	'Elsäkerhetsverket',
'https://www.ei.se':	'Energimarknadsinspektionen',
'https://www.etikprovning.se':	'Etikprövningsmyndigheten',
'https://www.ekn.se':	'Exportkreditnämnden',
'https://www.fmi.se':	'Fastighetsmäklarinspektionen',
'https://www.fi.se':	'Finansinspektionen',
'https://www.fpr.se':	'Finanspolitiska Rådet',
'https://www.fba.se':	'Folke Bernadotteakademin',
'https://www.folkhalsomyndigheten.se':	'Folkhälsomyndigheten',
'https://www.ftn.se':	'Fondtorgsnämnden',
'https://www.forskarskattenamnden.se':	'Forskarskattenämnden',
'https://www.formas.se':	'Forskningsrådet För Miljö, Areella Näringar Och Samhällsbyggande',
'https://www.forte.se':	'Forskningsrådet För Hälsa, Arbetsliv Och Välfärd',
'https://www.fortifikationsverket.se/':	'Fortifikationsverket',
'https://www.levandehistoria.se':	'Forum För Levande Historia',
'https://www.fmv.se':	'Försvarets Materielverk',
'https://www.fra.se':	'Försvarets Radioanstalt',
'https://www.fhs.se':	'Försvarshögskolan',
'https://www.forsvarsmakten.se':	'Försvarsmakten',
'https://www.forsakringskassan.se':	'Försäkringskassan',
'https://www.genteknik.se':	'Gentekniknämnden',
'https://www.gih.se':	'Gymnastik- Och Idrottshögskolan',
'https://www.gu.se':	'Göteborgs Universitet',
'https://www.harpsund.se':	'Harpsundsnämnden',
'https://www.havochvatten.se':	'Havs- Och Vattenmyndigheten',
'https://www.du.se':	'Högskolan Dalarna',
'https://www.hb.se':	'Högskolan I Borås',
'https://www.hig.se':	'Högskolan I Gävle',
'https://www.hh.se':	'Högskolan I Halmstad',
'https://www.hkr.se':	'Högskolan I Kristianstad',
'https://www.his.se':	'Högskolan I Skövde',
'https://www.hv.se':	'Högskolan Väst',
'https://www.han.se':	'Högskolans Avskiljandenämnd',
'https://svenskailo-kommitten.se/':	'Ilo-Kommittén',
'https://www.iaf.se':	'Inspektionen För Arbetslöshetsförsäkring',
'https://www.isf.se':	'Inspektionen För Socialförsäkringen',
'https://www.isp.se':	'Inspektionen För Strategiska Produkter',
'https://www.ivo.se':	'Inspektionen För Vård Och Omsorg',
'https://www.ifau.se':	'Institutet För Arbetsmarknads-Och Utbildningspolitisk Utvärdering',
'https://www.mrinstitutet.se':	'Institutet För Mänskliga Rättigheter',
'https://www.irf.se':	'Institutet För Rymdfysik',
'https://www.isof.se':	'Institutet För Språk Och Folkminnen',
'https://www.imy.se':	'Integritetsskyddsmyndigheten',
'https://www.jk.se':	'Justitiekanslern',
'https://www.jamstalldhetsmyndigheten.se':	'Jämställdhetsmyndigheten',
'https://www.kammarkollegiet.se':	'Kammarkollegiet',
'https://www.kau.se':	'Karlstads Universitet',
'https://www.ki.se':	'Karolinska Institutet',
'https://www.kemi.se':	'Kemikalieinspektionen',
'https://www.klimatpolitiskaradet.se':	'Klimatpolitiska Rådet',
'https://www.kommerskollegium.se':	'Kommerskollegium',
'https://www.konj.se':	'Konjunkturinstitutet',
'https://www.konkurrensverket.se':	'Konkurrensverket',
'https://www.konstfack.se':	'Konstfack',
'https://www.konstnarsnamnden.se':	'Konstnärsnämnden',
'https://www.konsumentverket.se':	'Konsumentverket',
'https://www.kriminalvarden.se':	'Kriminalvården',
'https://www.kronofogden.se':	'Kronofogdemyndigheten',
'https://www.kb.se':	'Kungliga Biblioteket',
'https://www.kkh.se':	'Kungliga Konsthögskolan',
'https://www.kmh.se':	'Kungliga Musikhögskolan',
'https://www.kth.se':	'Kungliga Tekniska Högskolan',
'https://www.kustbevakningen.se':	'Kustbevakningen',
'http://www.karnavfallsfonden.se':	'Kärnavfallsfonden (ENDAST HTTP)!',
'https://www.lagradet.se':	'Lagrådet',
'https://www.lantmateriet.se':	'Lantmäteriet',
'https://www.liu.se':	'Linköpings Universitet',
'https://www.lnu.se':	'Linnéuniversitetet',
'https://www.livsmedelsverket.se':	'Livsmedelsverket',
'https://www.ltu.se':	'Luleå Tekniska Universitet',
'https://www.lu.se':	'Lunds Universitet',
'https://www.lakemedelsverket.se':	'Läkemedelsverket',
'https://www.lansstyrelsen.se': 'Länsstyrelsen',
'https://www.mau.se':	'Malmö Universitet',
'https://www.mi.se':	'Medlingsinstitutet',
'https://www.miun.se':	'Mittuniversitetet',
'https://www.modernamuseet.se':	'Moderna Museet',
'https://www.mynak.se':	'Myndigheten För Arbetsmiljökunskap',
'https://www.mfd.se':	'Myndigheten För Delaktighet',
'https://www.digg.se':	'Myndigheten För Digital Förvaltning',
'https://www.mfof.se':	'Myndigheten För Familjerätt Och Föräldraskapsstöd',
'https://www.kulturanalys.se':	'Myndigheten För Kulturanalys',
'https://www.mprt.se':	'Myndigheten För Press, Radio Och Tv',
'https://www.mpf.se':	'Myndigheten För Psykologiskt Försvar',
'https://www.msb.se':	'Myndigheten För Samhällsskydd Och Beredskap (MSB)',
'https://www.myndighetensst.se':	'Myndigheten För Stöd Till Trossamfund',
'https://www.mtm.se':	'Myndigheten För Tillgängliga Medier',
'https://www.tillvaxtanalys.se':'Myndigheten För Tillväxtpolitiska Utvärderingar Och Analyser',
'https://www.mucf.se':'Myndigheten För Ungdoms-Och Civilsamhällesfrågor',
'https://www.vardanalys.se':'Myndigheten För Vård- Och Omsorgsanalys',
'https://www.myh.se':'Myndigheten För Yrkeshögskolan',
'https://www.mdu.se':'Mälardalens Universitet',
'https://www.nationalmuseum.se':'Nationalmuseum',
'https://www.nrm.se':	'Naturhistoriska Riksmuseet',
'https://www.naturvardsverket.se':	'Naturvårdsverket',
'https://www.nai.uu.se':	'Nordiska Afrikainstitutet',
'https://nfh.se':	'Nämnden För Hemslöjdsfrågor',
'https://www.namndenmotdiskriminering.se':	'Nämnden Mot Diskriminering',
'https://www.prv.se':	'Patent- Och Registreringsverket',
'https://www.polar.se':	'Polarforskningssekretariatet',
'https://www.polisen.se':	'Polismyndigheten',
'https://www.pts.se':	'Post- Och Telestyrelsen',
'https://www.regeringen.se':	'Regeringskansliet',
'https://www.revisorsinspektionen.se':	'Revisorsinspektionen',
'https://www.raa.se':	'Riksantikvarieämbetet',
'https://www.riksarkivet.se':	'Riksarkivet',
'https://www.riksgalden.se':	'Riksgäldskontoret',
'https://www.rymdstyrelsen.se':	'Rymdstyrelsen',
'https://www.rmv.se':	'Rättsmedicinalverket',
'https://www.sameskolstyrelsen.se':	'Sameskolstyrelsen',
'https://www.sametinget.se':	'Sametinget',
'https://www.sida.se':	'Sida',
'https://www.skatterattsnamnden.se':	'Skatterättsnämnden',
'https://www.skatteverket.se':	'Skatteverket',
'https://www.skogsstyrelsen.se':	'Skogsstyrelsen',
'https://www.skolfi.se':	'Skolforskningsinstitutet',
'https://www.overklagandenamnden.se':	'Skolväsendets Överklagandenämnd',
'https://www.socialstyrelsen.se':	'Socialstyrelsen',
'https://www.spsm.se':	'Specialpedagogiska Skolmyndigheten',
'https://www.spelinspektionen.se/':	'Spelinspektionen',
'https://www.statensansvarsnamnd.se':	'Statens Ansvarsnämnd',
'https://www.sbu.se':	'Statens Beredning För Medicinsk Och Social Utvärdering',
'https://www.arkdes.se':	'Statens Centrum För Arkitektur Och Design',
'https://www.energimyndigheten.se':	'Statens Energimyndighet',
'https://www.sfv.se':	'Statens Fastighetsverk',
'https://www.sfhm.se':	'Statens Försvarshistoriska Museer',
'https://www.swedgeo.se':	'Statens Geotekniska Institut',
'https://www.havkom.se':	'Statens Haverikommission',
'https://www.shm.se':	'Statens Historiska Museer',
'https://www.siun.se':	'Statens Inspektion För Försvarsunderrättelseverksamheten',
'https://www.stat-inst.se':	'Statens Institutionsstyrelse',
'https://www.jordbruksverket.se':	'Jordbruksverket',
'https://www.statenskonstrad.se':	'Statens Konstråd',
'https://www.kulturradet.se':	'Statens Kulturråd',
'https://www.smtm.se':	'Statens Maritima Och Transporthistoriska Museer',
'https://www.statensmedierad.se':	'Statens Medieråd',
'https://www.varldskulturmuseerna.se':	'Statens Museer För Världskultur',
'https://www.musikverket.se':	'Statens Musikverk',
'https://www.statenssc.se':	'Statens Servicecenter',
'https://www.skolinspektionen.se':	'Statens Skolinspektion',
'https://www.skolverket.se':	'Statens Skolverk',
'https://www.spv.se':	'Statens Tjänstepensionsverk',
'https://www.sva.se':	'Statens Veterinärmedicinska Anstalt',
'https://www.vti.se':	'Statens Väg- Och Transportforskningsinstitut',
'https://www.scb.se':	'Statistiska Centralbyrån',
'https://www.statskontoret.se':	'Statskontoret',
'https://www.uniarts.se':	'Stockholms Konstnärliga Högskola',
'https://www.su.se':	'Stockholms Universitet',
'https://www.stralsakerhetsmyndigheten.se':	'Strålsäkerhetsmyndigheten',
'https://www.swedac.se':	'Styrelsen För Ackreditering Och Teknisk Kontroll',
'https://www.sametinget.se/samefonden':	'Styrelsen För Samefonden',
'https://www.esf.se':	'Svenska Esf-Rådet',
'https://www.svenskafaokommitten.se':	'Svenska Fao-Kommittén',
'https://www.si.se':	'Svenska Institutet',
'https://www.sieps.se':	'Svenska Institutet För Europapolitiska Studier',
'https://www.svff.se':	'Sveriges Författarfond',
'https://www.sgu.se':	'Sveriges Geologiska Undersökning',
'https://www.slu.se':	'Sveriges Lantbruksuniversitet',
'https://www.smhi.se':	'Sveriges Meteorologiska Och Hydrologiska Institut',
'https://www.sakint.se':	'Säkerhets- Och Integritetsskyddsnämnden',
'https://www.sakerhetspolisen.se':	'Säkerhetspolisen',
'https://www.sh.se':	'Södertörns Högskola',
'https://www.tlv.se':	'Tandvårds-Och Läkemedelsförmånsverket',
'https://tillvaxtverket.se':	'Tillväxtverket',
'https://www.foi.se':	'Totalförsvarets Forskningsinstitut, Foi',
'https://www.pliktverket.se':	'Totalförsvarets Plikt- Och Prövningsverk',
'https://www.trafa.se':	'Trafikanalys',
'https://www.trafikverket.se':	'Trafikverket',
'https://www.transportstyrelsen.se':	'Transportstyrelsen',
'https://www.tullverket.se':	'Tullverket',
'https://www.umu.se':	'Umeå Universitet',
'https://www.uhr.se':	'Universitets- Och Högskolerådet',
'https://www.uka.se':	'Universitetskanslersämbetet',
'https://www.upphandlingsmyndigheten.se':	'Upphandlingsmyndigheten',
'https://www.uu.se':	'Uppsala Universitet',
'https://www.val.se':	'Valmyndigheten',
'https://www.vinnova.se':	'Verket För Innovationssystem',
'https://www.vr.se':	'Vetenskapsrådet',
'https://www.aklagare.se':	'Åklagarmyndigheten',
'https://www.oru.se':	'Örebro Universitet',
'https://www.onep.se':	'Överklagandenämnden För Etikprövning',
'https://www.onh.se':	'Överklagandenämnden För Högskolan',
'https://www.oks.se':	'Överklagandenämnden För Studiestöd',
'https://sl.se':    'Stockholms Länstrafik',
'https://www.sj.se':    'Statens Järnvägar',
'https://mtrx.travel':  'MTRX',
'https://www.flixtrain.com':    'Flix Train',
'https://www.arlandaexpress.se':    'Arlanda Express',
'https://www.oresundstag.se':   'Öresundståg',
'https://www.inlandsbanan.se':  'Inlandsbanan',
'https://www.skanetrafiken.se': 'Skånetrafiken / Pågatågen',
'https://www.vasttrafik.se':    'Västtågen',
'https://www.xtrafik.se':   'X-tåget',
'https://www.vy.se':    'Vy-tåg',
'http://www.varmlandstrafik.se':    'Värmlands Trafik',
'http://www.norrtag.se':    'Norrtåg',
'https://www.ostgotatrafiken.se':   'Östgötapendeln',
'https://malartag.se':  'Mälartåg',
'http://www.krosatagen.se': 'Krösatågen',
'https://www.snalltaget.se':    'Snälltåget',
'https://www.jlt.se':   'Jönköpings Länstrafik'
}